config/routes.rb
Rails3MongoidDevise::Application.routes.draw do
  

  resources :articulos

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/articulo.rb
class Articulo
  include Mongoid::Document
  field :titulo, type: String
  field :abstract, type: String
  field :description, type: String
  field :fecha, type: Date
  field :precio, type: Integer
  field :calificacion, type: Integer
  field :foto, type: String
  belongs_to :user
  embeds_many :keywords
  accepts_nested_attributes_for :keywords
end

app/models/keyword.rb
class Keyword
  include Mongoid::Document
  field :keyword, type: String
  embedded_in :articulo
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String
  field :profecion, :type => String
  field :reputacion, :type => String
  field :rol, :type => String
  field :foto, :type => String
  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  # run 'rake db:mongoid:create_indexes' to create indexes
  index({ email: 1 }, { unique: true, background: true })
  field :name, :type => String
  validates_presence_of :name
  attr_accessible :name, :email, :profecion,:reputacion,:rol,:foto,:password, :password_confirmation, :remember_me, :created_at, :updated_at
  has_many :articulos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  # GET /articulos
  # GET /articulos.json
  def index
    @articulos = Articulo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articulos }
    end
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
    @articulo = Articulo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @articulo }
    end
  end

  # GET /articulos/new
  # GET /articulos/new.json
  def new
    @articulo = Articulo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @articulo }
    end
  end

  # GET /articulos/1/edit
  def edit
    @articulo = Articulo.find(params[:id])
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(params[:articulo])

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo was successfully created.' }
        format.json { render json: @articulo, status: :created, location: @articulo }
      else
        format.html { render action: "new" }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articulos/1
  # PUT /articulos/1.json
  def update
    @articulo = Articulo.find(params[:id])

    respond_to do |format|
      if @articulo.update_attributes(params[:articulo])
        format.html { redirect_to @articulo, notice: 'Articulo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo = Articulo.find(params[:id])
    @articulo.destroy

    respond_to do |format|
      format.html { redirect_to articulos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articulos/_form.html.erb
<%= form_for(@articulo) do |f| %>
  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
      <% @articulo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br />
    <%= f.text_field :abstract %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :precio %><br />
    <%= f.number_field :precio %>
  </div>
  <div class="field">
    <%= f.label :calificacion %><br />
    <%= f.number_field :calificacion %>
  </div>
  <div class="field">
    <%= f.label :foto %><br />
    <%= f.text_field :foto %>
  </div>

   <%= f.collection_select :user_id, User.all, :id, :name %>
 <br>etiquetas <br>
<%= f.fields_for :keyword do |p| %>
  <%=p.text_field :keyword %>
<% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<h1>Editing articulo</h1>

<%= render 'form' %>

<%= link_to 'Show', @articulo %> |
<%= link_to 'Back', articulos_path %>

app/views/articulos/index.html.erb
<h1>Listing articulos</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Abstract</th>
    <th>Description</th>
    <th>Fecha</th>
    <th>Precio</th>
    <th>Calificacion</th>
    <th>Foto</th>
    <th>Usuario</th>
    <th></th>
    <th></th>
  </tr>

<% @articulos.each do |articulo| %>
  <tr>
    <td><%= articulo.titulo %></td>
    <td><%= articulo.abstract %></td>
    <td><%= articulo.description %></td>
    <td><%= articulo.fecha %></td>
    <td><%= articulo.precio %></td>
    <td><%= articulo.calificacion %></td>
    <td><%= articulo.foto %></td>
    <td><%= articulo.user.name %></td>
    <td><%= articulo.keywords%></td>
    <td><%= link_to 'Show', articulo %></td>
    <td><%= link_to 'Edit', edit_articulo_path(articulo) %></td>
    <td><%= link_to 'Destroy', articulo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Articulo', new_articulo_path %>

app/views/articulos/new.html.erb
<h1>New articulo</h1>

<%= render 'form' %>

<%= link_to 'Back', articulos_path %>

app/views/articulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @articulo.titulo %>
</p>

<p>
  <b>Abstract:</b>
  <%= @articulo.abstract %>
</p>

<p>
  <b>Description:</b>
  <%= @articulo.description %>
</p>

<p>
  <b>Fecha:</b>
  <%= @articulo.fecha %>
</p>

<p>
  <b>Precio:</b>
  <%= @articulo.precio %>
</p>

<p>
  <b>Calificacion:</b>
  <%= @articulo.calificacion %>
</p>

<p>
  <b>Foto:</b>
  <%= @articulo.foto %>
</p>


<%= link_to 'Edit', edit_articulo_path(@articulo) %> |
<%= link_to 'Back', articulos_path %>

app/views/home/index.html.erb
aqui todo el index ===> :D


holaaa

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Investico", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "investico" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Mongoid Devise" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>